package com.example

object PuzzleData {
    val puzzlePool = listOf(
        Pair("DROW", listOf("WORD", "ROW", "ROD")),
        Pair("ACTS", listOf("CATS", "CAT", "SAT", "ACT")),
        Pair("PLAY", listOf("PLAY", "LAY", "PAY", "LAP")),
        Pair("ARTS", listOf("STAR", "ART", "RAT", "SAT", "TAR")),
        Pair("LION", listOf("LION", "OIL", "NIL", "ION")),
        Pair("BOTA", listOf("BOAT", "BAT", "BOA", "TAB")),
        Pair("NOSE", listOf("NOSE", "SON", "ONE", "EON")),
        Pair("CLOD", listOf("COLD", "OLD", "COD", "DOC")),
        Pair("YARD", listOf("YARD", "RAY", "DAY", "DRY")),
        Pair("MONO", listOf("MOON", "NO", "ON", "MONO")),
        Pair("GOLD", listOf("GOLD", "GOD", "LOG", "OLD")),
        Pair("RIFE", listOf("RIFE", "FIRE", "FIR", "REF")),
        Pair("STOP", listOf("STOP", "POST", "POTS", "TOP", "POT")),
        Pair("EAST", listOf("EAST", "SEAT", "TEA", "EAT", "ATE")),
        Pair("DEER", listOf("DEER", "RED", "REED")),
        Pair("LINE", listOf("LINE", "NIL", "LIE")),
        Pair("WIND", listOf("WIND", "WIN", "DIN")),
        Pair("GAME", listOf("GAME", "MAGE", "GEM", "AGE")),
        Pair("LIFE", listOf("LIFE", "FILE", "ELF", "LIE")),
        Pair("WOLF", listOf("FLOW", "WOLF", "LOW", "OWL")),
        Pair("KABE", listOf("BAKE", "BEAK")), // Fixed: "CAB" cannot be spelled (no C)
        Pair("NEST", listOf("NEST", "NET", "TEN", "SENT")),
        Pair("PARK", listOf("PARK", "RAP", "ARK")),
        Pair("LUBE", listOf("BLUE", "LUBE", "BEL")),
        Pair("CLOA", listOf("COAL", "COLA", "LAC")),
        Pair("SUTR", listOf("RUST", "RUT", "RUTS")),
        Pair("SAPE", listOf("APES", "PEAS", "SPA", "ASP")),
        Pair("TEAM", listOf("TEAM", "MATE", "MEAT", "TAME", "TEA")),
        Pair("LAMP", listOf("LAMP", "PAL", "LAP", "MAP")),
        Pair("SINK", listOf("SINK", "INK", "KIN", "SKI")),
        Pair("COAT", listOf("COAT", "TACO", "CAT", "COT", "ACT")),
        Pair("ROSE", listOf("ROSE", "SORE", "ORE")),
        Pair("DRECK", listOf("DECK", "KED", "REC")),
        Pair("SANG", listOf("SANG", "NAG", "GAS", "SAG")),
        Pair("CORN", listOf("CORN", "CON", "NOR")),
        Pair("FROG", listOf("FROG", "FOR", "FOG")),
        Pair("RIDE", listOf("RIDE", "RED", "RID", "DIE")),
        Pair("FSIH", listOf("FISH", "HIS", "IFS")),
        Pair("MILK", listOf("MILK", "ILK", "MIL")),
        Pair("CARE", listOf("CARE", "RACE", "CAR", "ARC")),
        Pair("NOTE", listOf("NOTE", "TONE", "ONE", "TEN")),
        Pair("MARE", listOf("MARE", "REAM", "ARM", "EAR")),
        Pair("SALT", listOf("LAST", "SALT", "SAT", "ALT")),
        Pair("PEAR", listOf("PEAR", "REAP", "APE", "EAR")),
        Pair("RATE", listOf("RATE", "TEAR", "EAR", "ATE")),
        Pair("DARE", listOf("DARE", "READ", "RED", "DEAR")),
        Pair("MEAT", listOf("MEAT", "TEAM", "MATE", "TEA")),
        Pair("RING", listOf("RING", "GRIN", "GIN", "RIG")),
        Pair("TILE", listOf("TILE", "LITE", "LIE", "TIE")),

        Pair("CARE", listOf("ACRE", "RACE", "CAR", "ARE")),
        Pair("BEND", listOf("BEND", "BED", "END", "DEN")),
        Pair("FARM", listOf("FARM", "ARM", "FAR", "RAM")),
        Pair("MIND", listOf("MIND", "DIM", "DIN", "MID")),
        Pair("BIRD", listOf("BIRD", "RIB", "RID", "BID")),
        Pair("COIN", listOf("COIN", "ICON", "CON", "ION")),
        Pair("FISH", listOf("FISH", "HIS", "IF")), // Fixed redundant / non-standard "ISH"
        Pair("ROAD", listOf("ROAD", "ROD", "OAR", "ADO")),
        Pair("WAKE", listOf("WAKE", "WEAK", "AWE")), // Changed CAKE clone to WAKE to avoid duplicate keys and "AKE" spelling issue
        Pair("MOON", listOf("MOON", "MOO", "NO")), // Removed nonstandard "ONO"

        Pair("HAND", listOf("HAND", "AND", "HAD", "DNA")),
        Pair("SING", listOf("SING", "SIGN", "GIN", "SIN")),
        Pair("WARM", listOf("WARM", "ARM", "WAR", "RAM")),
        Pair("CAMP", listOf("CAMP", "MAP", "CAP", "AMP")),
        Pair("BELL", listOf("BELL", "ELL", "BEL")),
        Pair("KING", listOf("KING", "INK", "GIN", "KIN")),
        Pair("CORN", listOf("CORN", "CON", "NOR", "ROC")),
        Pair("FORK", listOf("FORK", "FOR")), // Simplified
        Pair("MILK", listOf("MILK", "ILK", "MIL")), // "KIM" is a name
        Pair("BOOK", listOf("BOOK", "BOO")), // "KOO" is nonstandard

        Pair("SNOW", listOf("SNOW", "NOW", "OWN", "SON")),
        Pair("TREE", listOf("TREE", "ERE", "TEE")),
        Pair("DUST", listOf("DUST", "STUD")), // Removed nonstandard/slang "DUS", "TUS"
        Pair("FLAG", listOf("FLAG", "LAG", "FAG", "GAL")),
        Pair("SHIP", listOf("SHIP", "HIP", "HIS", "SIP")),
        Pair("BRICK", listOf("BRICK", "RIB", "ICK")), // Removed double "BRICK" entry
        Pair("CHAIR", listOf("CHAIR", "HAIR", "AIR", "ARC")),
        Pair("PLANT", listOf("PLANT", "PLAN", "ANT", "TAN")),
        Pair("STONE", listOf("STONE", "NOTE", "TON", "ONE")),
        Pair("HOUSE", listOf("HOUSE", "USE", "SHE", "HOE")),

        Pair("APPLE", listOf("APPLE", "PAL", "PEA", "LAP")),
        Pair("MOUSE", listOf("MOUSE", "SUM", "USE")), // "MOE" is nonstandard / name
        Pair("TRAIN", listOf("TRAIN", "RAIN", "RAN", "ANT")),
        Pair("PLANE", listOf("PLANE", "PEN", "LAP", "LEAN")),
        Pair("CROWN", listOf("CROWN", "COW", "NOW", "OWN")),
        Pair("HEART", listOf("HEART", "HEAR", "RATE", "EAR")),
        Pair("LIGHT", listOf("LIGHT", "HIT", "LIT")), // Removed "GIT"
        Pair("SMILE", listOf("SMILE", "LIME", "MILE", "LIE")),
        Pair("BRAIN", listOf("BRAIN", "RAIN", "RAN", "AIR")),
        Pair("SWEET", listOf("SWEET", "WEST", "SEE", "TEE")),

        Pair("CLEAN", listOf("CLEAN", "LACE", "CAN", "LEAN")),
        Pair("SUGAR", listOf("SUGAR", "RAG", "RUG", "SAG")),
        Pair("WATER", listOf("WATER", "WEAR", "RATE", "TEAR")),
        Pair("POWER", listOf("POWER", "PORE", "ROW", "ORE")),
        Pair("GREEN", listOf("GREEN", "GENE", "ERG", "NEE")),
        Pair("BLACK", listOf("BLACK", "BACK", "LACK", "CAB")),
        Pair("WHITE", listOf("WHITE", "WITH", "HIT", "THE")),
        Pair("BROWN", listOf("BROWN", "OWN", "ROW", "NOW")),
        Pair("PINK", listOf("PINK", "INK", "PIN", "KIN")),
        Pair("ORANGE", listOf("ORANGE", "RAGE", "ONE", "RAN")),

        Pair("PURPLE", listOf("PURPLE", "PURE", "RULE", "PER")),
        Pair("YELLOW", listOf("YELLOW", "YELL", "LOW", "OWL")),
        Pair("MARKET", listOf("MARKET", "MAKE", "RATE", "TEAM", "TEAR")),
        Pair("POCKET", listOf("POCKET", "POKE", "TOP", "COP")),
        Pair("GARDEN", listOf("GARDEN", "DANGER", "RAG", "DEN")),
        Pair("BOTTLE", listOf("BOTTLE", "BOLT", "LOT")), // Removed "TEL"
        Pair("SCHOOL", listOf("SCHOOL", "COOL", "SOLO", "COL")),
        Pair("PENCIL", listOf("PENCIL", "CLIP", "PEN", "NIL")),
        Pair("WINDOW", listOf("WINDOW", "WIND", "OWN", "NOW")),
        Pair("MARKER", listOf("MARKER", "MAKE", "ARM", "EAR")),

        Pair("BUTTON", listOf("BUTTON", "TON", "NOT", "BUT")),
        Pair("STREAM", listOf("STREAM", "MASTER", "TEAM", "RATE")),
        Pair("FLOWER", listOf("FLOWER", "WOLF", "LOW", "ROW")),
        Pair("PLANET", listOf("PLANET", "PLANE", "LATE", "NET")),
        Pair("MONKEY", listOf("MONKEY", "KEY", "MEN", "ONE")),
        Pair("JACKET", listOf("JACKET", "JACK", "TAKE", "TEA")),
        Pair("BASKET", listOf("BASKET", "BAKE", "SEAT", "TAB")),
        Pair("FATHER", listOf("FATHER", "HEAR", "RATE", "FAR")),
        Pair("MOTHER", listOf("MOTHER", "HOME", "MORE", "THE")),
        Pair("SISTER", listOf("SISTER", "SITE", "REST", "TIRE")),

        Pair("BROTHER", listOf("BROTHER", "OTHER", "HER", "HOT")),
        Pair("FRIEND", listOf("FRIEND", "FIND", "RED", "END")),
        Pair("BREAD", listOf("BREAD", "BEAR", "READ", "RED")),
        Pair("BUTTER", listOf("BUTTER", "TUBE", "RUB", "BET")),
        Pair("CHEESE", listOf("CHEESE", "SEE", "SHE")), // Removed nonstandard "CHEE"
        Pair("MARKS", listOf("MARKS", "MASK", "ARK", "ARM")),
        Pair("CIRCLE", listOf("CIRCLE", "CLERIC", "ICE", "LIE")),
        Pair("SQUARE", listOf("SQUARE", "SURE", "USER", "SEA")),
        Pair("TRIANGLE", listOf("TRIANGLE", "ANGLE", "RING", "ANT")),
        Pair("COUNTRY", listOf("COUNTRY", "COUNT", "TON", "TRY")),

        Pair("AFRICA", listOf("AFRICA", "AIR", "CAR", "ARC")),
        Pair("NIGERIA", listOf("NIGERIA", "RAIN", "RAGE", "GIN")),
        Pair("LONDON", listOf("LONDON", "DON", "OLD", "NOD")),
        Pair("CANADA", listOf("CANADA", "CAN", "AND")), // Removed nonstandard/name "ADA"
        Pair("BRAZIL", listOf("BRAZIL", "RAIL", "AIR", "LAB")),
        Pair("TOKYO", listOf("TOKYO", "TOY", "TOO")), // Removed nonstandard "YOK"
        Pair("PARIS", listOf("PARIS", "PAIR", "AIR", "SAP")),
        Pair("BERLIN", listOf("BERLIN", "LINE", "BIN", "RIB")),
        Pair("DUBAI", listOf("DUBAI", "AID", "BAD", "DUB")),
        Pair("LAGOS", listOf("LAGOS", "GOAL", "GAS", "SAG")),

        Pair("BEACH", listOf("BEACH", "ACHE", "EACH", "CAB")),
        Pair("RIVER", listOf("RIVER", "RIVE", "VIE", "ERR")),
        Pair("MOUNTAIN", listOf("MOUNTAIN", "MOUNT", "ANTI", "TIN")),
        Pair("VALLEY", listOf("VALLEY", "ALLY", "LAY", "YELL")),
        Pair("DESERT", listOf("DESERT", "REST", "TREE", "RED")),
        Pair("FOREST", listOf("FOREST", "SOFT", "ROSE", "TORE")),
        Pair("ISLAND", listOf("ISLAND", "LAND", "SAIL", "SAND")),
        Pair("JUNGLE", listOf("JUNGLE", "GLUE", "LUNG", "GEL")),
        Pair("OCEAN", listOf("OCEAN", "CANE", "ONE", "CAN")),
        Pair("CASTLE", listOf("CASTLE", "LACE", "SEAT", "CAT")),

        Pair("BRIDGE", listOf("BRIDGE", "BIRD", "GRID", "RIDE")),
        Pair("MARKET", listOf("MARKET", "MAKE", "RATE", "TEAM", "TEAR")),
        Pair("VILLAGE", listOf("VILLAGE", "VIAL", "GAVE", "LIVE")),
        Pair("SCHOOL", listOf("SCHOOL", "COOL", "SOLO", "COL")),
        Pair("COLLEGE", listOf("COLLEGE", "CELL", "LOG", "LEG")),
        Pair("LIBRARY", listOf("LIBRARY", "RAIL", "AIR", "BAR")),
        Pair("HOSPITAL", listOf("HOSPITAL", "PATH", "SHIP", "POST")),
        Pair("OFFICE", listOf("OFFICE", "ICE", "OFF")), // Removed nonstandard "COFF"
        Pair("FACTORY", listOf("FACTORY", "FACTOR", "ART", "TOY")),
        Pair("STATION", listOf("STATION", "ANTI", "TON", "SIT")),

        Pair("ENGINE", listOf("ENGINE", "GENIE", "NINE", "GIN")),
        Pair("TRACTOR", listOf("TRACTOR", "ACTOR", "CAR", "ART")),
        Pair("BICYCLE", listOf("BICYCLE", "CYCLE", "ICE", "LIE")),
        Pair("AIRPORT", listOf("AIRPORT", "TRAP", "PORT", "PAIR")),
        Pair("JOURNEY", listOf("JOURNEY", "YOUR", "RUN", "JOY")),
        Pair("TICKET", listOf("TICKET", "KITE", "TIE", "ICE")),
        Pair("LUGGAGE", listOf("LUGGAGE", "GALE", "AGE", "LUG")),
        Pair("SAILOR", listOf("SAILOR", "SAIL", "SOAR", "AIR")),
        Pair("CAPTAIN", listOf("CAPTAIN", "PAINT", "ANTI", "CAP")),
        Pair("ROCKET", listOf("ROCKET", "ROCK", "TORE", "CORE")),

        Pair("PLANET", listOf("PLANET", "PLANE", "LATE", "NET")),
        Pair("GALAXY", listOf("GALAXY", "GALA", "LAY", "GAY", "LAG")),
        Pair("ASTEROID", listOf("ASTEROID", "STAR", "ROAD", "TIDE")),
        Pair("COMET", listOf("COMET", "COME", "TOE", "MET")),
        Pair("SATURN", listOf("SATURN", "TURN", "RUST", "SUN")),
        Pair("NEPTUNE", listOf("NEPTUNE", "TUNE", "PEN", "TEN")),
        Pair("MERCURY", listOf("MERCURY", "CURE", "RUM", "CRY")),
        Pair("JUPITER", listOf("JUPITER", "TRIP", "RITE", "JET")),
        Pair("VENUS", listOf("VENUS", "SUN", "USE", "SUE")),
        Pair("EARTH", listOf("EARTH", "HEAR", "HAT", "RATE")),

        Pair("BANANA", listOf("BANANA", "BAN", "NAB")), // Removed "ANA"
        Pair("ORANGE", listOf("ORANGE", "RANGE", "RAGE", "ONE")),
        Pair("PAPAYA", listOf("PAPAYA", "PAY", "PAPA", "YAP")),
        Pair("MANGO", listOf("MANGO", "MAN", "AGO")), // Removed non-standard "GOAN"
        Pair("TOMATO", listOf("TOMATO", "ATOM", "TOO", "MAT")),
        Pair("POTATO", listOf("POTATO", "TOP", "TOO", "PAT")),
        Pair("CARROT", listOf("CARROT", "CART", "TAR", "ROT")),
        Pair("CUCUMBER", listOf("CUCUMBER", "CUBE", "CURB", "BERM")),
        Pair("ONION", listOf("ONION", "ION", "NO")), // Removed "NON"
        Pair("PEPPER", listOf("PEPPER", "PEER", "PER", "REP")),

        Pair("CHICKEN", listOf("CHICKEN", "CHECK", "HEN", "INK")),
        Pair("SAUSAGE", listOf("SAUSAGE", "SAGE", "AGE", "USE")),
        Pair("BISCUIT", listOf("BISCUIT", "SUIT", "BITS", "BUS")),
        Pair("NOODLES", listOf("NOODLES", "NOSE", "DONE", "LOSE")),
        Pair("SPAGHETTI", listOf("SPAGHETTI", "SPIT", "HAT", "GET")),
        Pair("BURGER", listOf("BURGER", "RUG", "BUG", "RUB")),
        Pair("SANDWICH", listOf("SANDWICH", "SAND", "WASH", "HAND")),
        Pair("PIZZA", listOf("PIZZA", "ZIP", "PI")), // Removed "PAZ"
        Pair("CHOCOLATE", listOf("CHOCOLATE", "COAT", "LATE", "COLA")),
        Pair("ICECREAM", listOf("ICECREAM", "CREAM", "RACE", "ICE")),

        Pair("DOCTOR", listOf("DOCTOR", "CORD", "ROOT", "DOT")),
        Pair("NURSE", listOf("NURSE", "SURE", "RUN", "SUN")),
        Pair("TEACHER", listOf("TEACHER", "CHEAT", "HEAR", "TEA")),
        Pair("LAWYER", listOf("LAWYER", "WEAR", "YEAR", "LAY")),
        Pair("POLICE", listOf("POLICE", "COIL", "LICE", "ICE")),
        Pair("FARMER", listOf("FARMER", "FRAME", "ARM", "FAR")),
        Pair("PILOT", listOf("PILOT", "PLOT", "TIP", "LIP")),
        Pair("DRIVER", listOf("DRIVER", "RIDE", "DIVE")), // Removed "RIV"
        Pair("SINGER", listOf("SINGER", "SIGN", "RING", "SIN")),
        Pair("DANCER", listOf("DANCER", "DANCE", "CARE", "RED")),

        Pair("GUITAR", listOf("GUITAR", "RUG", "AIR", "TAG")),
        Pair("PIANO", listOf("PIANO", "PAIN", "NAP", "PIN")),
        Pair("DRUM", listOf("DRUM", "MUD", "RUM")), // Removed "DRU"
        Pair("TRUMPET", listOf("TRUMPET", "TRUMP", "TRUE", "PET")),
        Pair("VIOLIN", listOf("VIOLIN", "LION", "OIL", "NIL")),
        Pair("FLUTE", listOf("FLUTE", "LEFT", "FELT", "LET")),
        Pair("MUSIC", listOf("MUSIC", "SUM")), // Removed "CUS", "MUS"
        Pair("MELODY", listOf("MELODY", "MOLD", "DOME", "DEMO")),
        Pair("RHYTHM", listOf("RHYTHM", "MYTH", "TRY", "THY")),
        Pair("DANCING", listOf("DANCING", "DING", "GAIN", "CAN")),

        Pair("NAVY", listOf("NAVY", "VAN", "ANY", "NAY")), // Changed "JAVA" (which had unspellable "JAR"/"VAN") to NAVY

        Pair("ELEPHANT", listOf("ELEPHANT", "PLANT", "HEAT", "PEN")),
        Pair("GIRAFFE", listOf("GIRAFFE", "RAGE", "GEAR", "FEAR")),
        Pair("CROCODILE", listOf("CROCODILE", "COIL", "CODE", "RIDE")),
        Pair("KANGAROO", listOf("KANGAROO", "KANGA", "ROAN", "RANG")),
        Pair("DOLPHIN", listOf("DOLPHIN", "HOLD", "LION", "HOP")),
        Pair("BUTTERFLY", listOf("BUTTERFLY", "FLY", "TRUE", "BUTTER")),
        Pair("MOSQUITO", listOf("MOSQUITO", "MOST", "QUIT", "SIT")),
        Pair("CHEETAH", listOf("CHEETAH", "HEAT", "CHAT", "HATE")),
        Pair("PENGUIN", listOf("PENGUIN", "PEN", "GUN", "NINE")),
        Pair("CAT", listOf("CAT", "ACT")),
    Pair("DOG", listOf("DOG", "GOD")),
    Pair("BAT", listOf("BAT", "TAB")),
    Pair("BUS", listOf("BUS", "SUB")),
    Pair("CAR", listOf("CAR", "ARC")),
    Pair("ARM", listOf("ARM", "RAM")),
    Pair("ART", listOf("ART", "RAT", "TAR")),
    Pair("EAT", listOf("EAT", "ATE", "TEA")),
    Pair("NET", listOf("NET", "TEN")),
    Pair("PEN", listOf("PEN")),
    Pair("PIN", listOf("PIN", "NIP")),
    Pair("POT", listOf("POT", "TOP")),
    Pair("TIP", listOf("TIP", "PIT")),
    Pair("PAN", listOf("PAN", "NAP")),
    Pair("TAP", listOf("TAP", "PAT", "APT")),
    Pair("SAW", listOf("SAW", "WAS")),
    Pair("SUN", listOf("SUN")),
    Pair("RUN", listOf("RUN", "URN")),
    Pair("WIN", listOf("WIN")),
    Pair("GUN", listOf("GUN")),

    // 4-Letter Base Words
    Pair("CARE", listOf("CARE", "RACE", "ACRE", "CAR", "ARC", "ARE")),
    Pair("NOTE", listOf("NOTE", "TONE", "TOE", "TON", "ONE", "TEN")),
    Pair("MARE", listOf("MARE", "REAM", "ARM", "RAM", "EAR", "ARE")),
    Pair("SALT", listOf("SALT", "LAST", "SLAT", "SAT", "ALT")),
    Pair("PEAR", listOf("PEAR", "REAP", "RAPE", "APE", "PEA", "EAR")),
    Pair("RATE", listOf("RATE", "TEAR", "TARE", "EAR", "ATE", "ART")),
    Pair("DARE", listOf("DARE", "READ", "DEAR", "RED", "EAR", "RAD")),
    Pair("MEAT", listOf("MEAT", "TEAM", "MATE", "TAME", "TEA", "MAT")),
    Pair("RING", listOf("RING", "GRIN", "GIN", "RIG")),
    Pair("TILE", listOf("TILE", "LITE", "LIE", "TIE", "LIT")),
    Pair("BEND", listOf("BEND", "BED", "END", "DEN")),
    Pair("FARM", listOf("FARM", "ARM", "FAR", "RAM")),
    Pair("MIND", listOf("MIND", "DIM", "DIN", "MID")),
    Pair("BIRD", listOf("BIRD", "RIB", "RID", "BID")),
    Pair("COIN", listOf("COIN", "ICON", "CON", "ION")),
    Pair("FISH", listOf("FISH", "HIS", "IFS")),
    Pair("ROAD", listOf("ROAD", "ROD", "OAR", "ADO")),
    Pair("CAKE", listOf("CAKE", "ACE", "AKE")),
    Pair("MOON", listOf("MOON", "MOO")),
    Pair("HAND", listOf("HAND", "AND", "HAD", "DNA")),
    Pair("SING", listOf("SING", "SIGN", "GIN", "SIN")),
    Pair("WARM", listOf("WARM", "ARM", "WAR", "RAM")),
    Pair("CAMP", listOf("CAMP", "MAP", "CAP", "AMP")),
    Pair("BELL", listOf("BELL", "ELL", "BEL")),
    Pair("KING", listOf("KING", "INK", "GIN", "KIN")),
    Pair("CORN", listOf("CORN", "CON", "NOR")),
    Pair("FORK", listOf("FORK", "FOR", "ROK")),
    Pair("MILK", listOf("MILK", "ILK", "MIL")),
    Pair("BOOK", listOf("BOOK", "BOO")),
    Pair("SNOW", listOf("SNOW", "NOW", "OWN", "SON")),
    Pair("TREE", listOf("TREE", "TEE", "ERE")),
    Pair("DUST", listOf("DUST", "STUD", "DUS")),
    Pair("FLAG", listOf("FLAG", "LAG", "FAG", "GAL")),
    Pair("SHIP", listOf("SHIP", "HIP", "HIS", "SIP")),
    Pair("BEACH", listOf("BEACH", "ACHE", "EACH", "CAB")),
    Pair("RIVER", listOf("RIVER", "RIVE", "VIE")),
    Pair("OCEAN", listOf("OCEAN", "CANE", "CONE", "CAN", "ONE")),
    Pair("BEAR", listOf("BEAR", "BARE", "BAR", "EAR", "ARE")),
    Pair("LION", listOf("LION", "LOIN", "NIL", "ION")),
    Pair("WOLF", listOf("WOLF", "FLOW", "FOWL", "LOW")),
    Pair("DEER", listOf("DEER", "REED", "RED")),
    Pair("DUCK", listOf("DUCK")),
    Pair("FROG", listOf("FROG", "FOR", "FOG")),
    Pair("CROW", listOf("CROW", "COW", "ROW")),
    Pair("SWAN", listOf("SWAN", "SAW", "WAN")),
    Pair("SEAL", listOf("SEAL", "SALE", "LEAS", "SEA", "ALE")),
    Pair("MOLE", listOf("MOLE", "ELM")),
    Pair("GOAT", listOf("GOAT", "TOGA", "GOT", "TAG", "OAT")),
    Pair("LAMP", listOf("LAMP", "PALM", "MAP", "PAL", "LAP")),
    Pair("DOOR", listOf("DOOR", "ROD")),
    Pair("ROOF", listOf("ROOF", "FOR")),
    Pair("DESK", listOf("DESK")),
    Pair("SOFA", listOf("SOFA", "FAS")),
    Pair("GATE", listOf("GATE", "GET", "ATE", "TAG")),

    // 5-Letter Base Words
    Pair("BRICK", listOf("BRICK", "CRIB", "RIB", "ICK")),
    Pair("CHAIR", listOf("CHAIR", "ARCH", "HAIR", "RICH", "AIR", "ARC")),
    Pair("PLANT", listOf("PLANT", "PLAN", "PLAT", "ANT", "TAN", "PAN")),
    Pair("STONE", listOf("STONE", "TONE", "NOTE", "NEST", "TON", "ONE", "TEN")),
    Pair("HOUSE", listOf("HOUSE", "SHOE", "HOSE", "USE", "SHE")),
    Pair("APPLE", listOf("APPLE", "PEAL", "LEAP", "PAL", "PEA", "LAP")),
    Pair("MOUSE", listOf("MOUSE", "MUSE", "SOME", "SUM", "USE")),
    Pair("TRAIN", listOf("TRAIN", "RAIN", "RAN", "TIN", "ANT", "TAN")),
    Pair("PLANE", listOf("PLANE", "PANEL", "PLAN", "LANE", "PEN", "PAN", "LAP")),
    Pair("CROWN", listOf("CROWN", "CORN", "CROW", "COW", "NOW", "OWN")),
    Pair("HEART", listOf("HEART", "EARTH", "HEAR", "HEAT", "RATE", "TEAR", "EAR", "ART")),
    Pair("LIGHT", listOf("LIGHT", "LIT", "HIT")),
    Pair("SMILE", listOf("SMILE", "SLIME", "MILE", "LIME", "SLIM", "LIE")),
    Pair("BRAIN", listOf("BRAIN", "RAIN", "BARN", "BRAN", "AIR", "BAN", "RAN")),
    Pair("SWEET", listOf("SWEET", "WEST", "TEES", "SEE", "TEE")),
    Pair("CLEAN", listOf("CLEAN", "LANCE", "LANE", "LEAN", "CAN")),
    Pair("SUGAR", listOf("SUGAR", "ARGUS", "RAG", "RUG", "SAG")),
    Pair("WATER", listOf("WATER", "WEAR", "TEAR", "RATE", "WARE", "WET", "ATE", "ART")),
    Pair("POWER", listOf("POWER", "PORE", "ROPE", "PROW", "ROW", "ORE", "PER")),
    Pair("GREEN", listOf("GREEN", "GENE", "GRENE", "NEE")),
    Pair("BLACK", listOf("BLACK", "BACK", "LACK", "CAB")),
    Pair("WHITE", listOf("WHITE", "WITH", "WHET", "HIT", "TIE")),
    Pair("BROWN", listOf("BROWN", "BORN", "BROW", "OWN", "ROW", "NOW")),
    Pair("MARKS", listOf("MARKS", "MASK", "MARK", "ARK", "ARM", "RAM")),
    Pair("DANCE", listOf("DANCE", "CANE", "ACNE", "CAN", "DEN", "END")),
    Pair("STORM", listOf("STORM", "MOST", "SORT", "MORT", "ROT", "TOM")),
    Pair("CLIMB", listOf("CLIMB", "LIMB", "MIC")),
    Pair("DRIVE", listOf("DRIVE", "RIDE", "DIVE", "DIRE", "RED")),
    Pair("SHIRT", listOf("SHIRT", "THIS", "HIT", "SIT")),
    Pair("PANEL", listOf("PANEL", "PLANE", "PLAN", "LANE", "PEN", "NAP")),
    Pair("FRAME", listOf("FRAME", "FARM", "MARE", "FEAR", "ARM", "RAM", "FAR")),
    Pair("TIGER", listOf("TIGER", "TIER", "GRIT", "TIE", "GET")),
    Pair("EAGLE", listOf("EAGLE", "GALE", "AGE", "ALE")),
    Pair("SHARK", listOf("SHARK", "HARK", "ARK", "ASH")),
    Pair("HORSE", listOf("HORSE", "SHORE", "HOSE", "HERO", "HER")),
    Pair("ZEBRA", listOf("ZEBRA", "BARE", "BEAR", "BAR", "BRA", "EAR")),
    Pair("CAMEL", listOf("CAMEL", "MALE", "LAME", "CAM")),
    Pair("PANDA", listOf("PANDA", "PAD", "PAN", "ANA")),
    Pair("KOALA", listOf("KOALA", "ALAK")),
    Pair("OTTER", listOf("OTTER", "TOTE", "ROTE", "TOE")),
    Pair("SNAKE", listOf("SNAKE", "SANK", "AKE", "ASK")),
    Pair("LEMON", listOf("LEMON", "MELON", "MOLE", "ONE", "MEN")),
    Pair("PEACH", listOf("PEACH", "CHEAP", "EACH", "ACE", "APE", "CAP")),
    Pair("GRAPE", listOf("GRAPE", "PAGER", "PAGE", "PEAR", "RAPE", "APE", "EAR")),
    Pair("MELON", listOf("MELON", "LEMON", "MOLE", "ONE", "MEN")),
    Pair("BREAD", listOf("BREAD", "BEAR", "BARD", "BEAD", "READ", "RED", "BAD")),
    Pair("CLOCK", listOf("CLOCK", "LOCK", "COCK")),
    Pair("TABLE", listOf("TABLE", "ABLE", "BEAT", "BETA", "TAB", "BAT", "ALE")),
    Pair("RADIO", listOf("RADIO", "RAID", "ROAD", "RID", "RAD")),
    Pair("PHONE", listOf("PHONE", "OPEN", "PEN", "EON")),
    Pair("PAPER", listOf("PAPER", "REAP", "PEAR", "RAPE", "APE", "PAR")),
    Pair("TOWEL", listOf("TOWEL", "LOTE", "LOW", "TOW", "TOE")),
    Pair("SHOWER", listOf("SHOWER", "SHOW", "SHORE", "HERO", "ROW")),
    Pair("CLOSET", listOf("CLOSET", "CLOSE", "COST", "TOE")),

    // 6-Letter Base Words
    Pair("MARKET", listOf("MARKET", "MAKE", "RATE", "TEAM", "TEAR", "MARE", "MEAT", "MAT", "ARM", "ART")),
    Pair("POCKET", listOf("POCKET", "POKE", "COPE", "TOP", "POT", "COP", "PET")),
    Pair("GARDEN", listOf("GARDEN", "DANGER", "RAGE", "GEAR", "READ", "DEAR", "DEN", "RED", "RAG", "AGE")),
    Pair("BOTTLE", listOf("BOTTLE", "BOLT", "BLOT", "LOB", "LOT", "TOE")),
    Pair("SCHOOL", listOf("SCHOOL", "COOL", "SOLO", "LOCO", "COOS")),
    Pair("PENCIL", listOf("PENCIL", "CLIP", "LINE", "NIL", "PIN", "PEN", "LIE")),
    Pair("WINDOW", listOf("WINDOW", "WIND", "DOWN", "OWN", "WIN", "NOW")),
    Pair("MARKER", listOf("MARKER", "MAKE", "MARE", "MARK", "RARE", "REAR", "ARM", "RAM", "EAR")),
    Pair("BUTTON", listOf("BUTTON", "UNTO", "TON", "NOT", "BUT", "TUB")),
    Pair("STREAM", listOf("STREAM", "MASTER", "STEAM", "TEAM", "MEAT", "RATE", "TEAR", "MARE", "MAT", "ARM")),
    Pair("FLOWER", listOf("FLOWER", "WOLF", "FLOW", "FOWL", "LORE", "ROLE", "LOW", "ROW", "FOR")),
    Pair("PLANET", listOf("PLANET", "PLANE", "PANEL", "PLANT", "PLATE", "LATE", "LANE", "PEAT", "NET", "PET")),
    Pair("MONKEY", listOf("MONKEY", "YOKE", "OMEN", "KEY", "MEN", "ONE")),
    Pair("JACKET", listOf("JACKET", "JACK", "TAKE", "TEAK", "ACT", "JET", "TEA")),
    Pair("BASKET", listOf("BASKET", "BAKE", "BEAK", "BEAT", "BETA", "SEAT", "EAST", "ASK", "BAT", "TAB")),
    Pair("FATHER", listOf("FATHER", "HEAR", "HEAT", "RATE", "TEAR", "FEAR", "FATE", "FAR", "HAT", "ART")),
    Pair("MOTHER", listOf("MOTHER", "HOME", "MORE", "HERO", "ROTE", "TERM", "HER", "HOT", "TOE")),
    Pair("SISTER", listOf("SISTER", "RESIST", "SITE", "REST", "RISE", "TIRE", "SET", "SIT")),
    Pair("AFRICA", listOf("AFRICA", "FAIR", "AFAR", "AIR", "CAR", "ARC", "FAR")),
    Pair("NIGERIA", listOf("NIGERIA", "RAIN", "GAIN", "RAGE", "GEAR", "GIN", "AIR")),
    Pair("LONDON", listOf("LONDON", "LOON", "DON", "OLD", "NOD")),
    Pair("CANADA", listOf("CANADA", "CAN", "ANA")),
    Pair("BRAZIL", listOf("BRAZIL", "RAIL", "LIAR", "BRAI", "AIR", "BAR", "LAB")),
    Pair("BERLIN", listOf("BERLIN", "LINE", "RILE", "BILE", "BIN", "RIB", "NIL")),
    Pair("CASTLE", listOf("CASTLE", "LACE", "CASE", "SEAT", "EAST", "LATE", "TALE", "CAT", "ACT", "ALE")),
    Pair("BRIDGE", listOf("BRIDGE", "BIRD", "RIDE", "GRID", "DIRE", "BIG", "RED", "RIB")),
    Pair("VILLAGE", listOf("VILLAGE", "VIAL", "GAVE", "GALE", "EVIL", "LIVE", "LEG", "AGE")),
    Pair("COLLEGE", listOf("COLLEGE", "CELL", "LOGE", "OGLE", "LOG", "LEG")),
    Pair("LIBRARY", listOf("LIBRARY", "RAIL", "LIAR", "AIR", "BAR", "RAY")),
    Pair("OFFICE", listOf("OFFICE", "COFF", "FICE", "ICE", "OFF")),
    Pair("FACTORY", listOf("FACTORY", "FACTOR", "ACTOR", "CRAFT", "COAT", "CART", "ART", "TOY", "CAT")),
    Pair("STATION", listOf("STATION", "SATIN", "ANTI", "INTO", "STIN", "TON", "NOT", "SIT")),
    Pair("ENGINE", listOf("ENGINE", "GENIE", "NINE", "GIN")),
    Pair("TRACTOR", listOf("TRACTOR", "ACTOR", "TRACT", "COAT", "CART", "CAR", "ART", "CAT")),
    Pair("BICYCLE", listOf("BICYCLE", "CYCLE", "CICE", "ICE", "LIE")),
    Pair("AIRPORT", listOf("AIRPORT", "PORT", "PART", "RAPT", "TRAP", "PAIR", "AIR", "PAR", "TOP")),
    Pair("JOURNEY", listOf("JOURNEY", "YOUR", "JURY", "RUNE", "RUN", "JOY")),
    Pair("TICKET", listOf("TICKET", "KITE", "TIE", "ICE")),
    Pair("LUGGAGE", listOf("LUGGAGE", "GALE", "GAUG", "AGE", "LUG", "GAG")),
    Pair("SAILOR", listOf("SAILOR", "SAIL", "SOAR", "SILO", "LIAR", "RAIL", "AIR")),
    Pair("CAPTAIN", listOf("CAPTAIN", "PAINT", "PAIN", "ANTI", "PINT", "CAP", "PAN", "CAT", "TAN")),
    Pair("ROCKET", listOf("ROCKET", "ROCK", "CORK", "COTE", "TORE", "CORE", "ROT", "TOE")),
    Pair("GALAXY", listOf("GALAXY", "GALA", "AGAL", "LAY", "GAL")),
    Pair("MERCURY", listOf("MERCURY", "CURE", "CURY", "RUM", "CRY")),
    Pair("JUPITER", listOf("JUPITER", "TRIP", "RIPE", "RITE", "TIER", "JET", "PET", "TIE")),
    Pair("ORANGE", listOf("ORANGE", "RANGE", "ORGAN", "GROAN", "RAGE", "GEAR", "GONE", "ONE", "RAN", "AGE")),
    Pair("PAPAYA", listOf("PAPAYA", "PAPA", "PAY", "YAP")),
    Pair("BANANA", listOf("BANANA", "BAN", "ANA")),
    Pair("CARROT", listOf("CARROT", "CART", "COAT", "ROTA", "TAR", "ROT", "CAT")),
    Pair("PEPPER", listOf("PEPPER", "PREP", "PEER", "PER", "REP")),
    Pair("CHICKEN", listOf("CHICKEN", "CHECK", "CHIN", "INCH", "HIKE", "HEN", "INK")),
    Pair("SAUSAGE", listOf("SAUSAGE", "USAGE", "SAGE", "GAS", "AGE", "USE")),
    Pair("BISCUIT", listOf("BISCUIT", "SUIT", "BITS", "CUST", "BUS", "BIT", "SIT")),
    Pair("BURGER", listOf("BURGER", "URGE", "RUG", "BUG", "RUB")),
    Pair("DOCTOR", listOf("DOCTOR", "CORD", "ROOT", "ODOR", "DOT", "ROD")),
    Pair("TEACHER", listOf("TEACHER", "CHEAT", "REACH", "HEART", "EARTH", "TEAR", "RATE", "TEA", "CAT", "HAT")),
    Pair("LAWYER", listOf("LAWYER", "WEAR", "YEAR", "LYRE", "WAR", "LAY", "RAW")),
    Pair("POLICE", listOf("POLICE", "COIL", "LICE", "POLE", "CLIP", "ICE", "COP", "LIP")),
    Pair("FARMER", listOf("FARMER", "FRAME", "FARM", "MARE", "FEAR", "RARE", "ARM", "FAR", "RAM")),
    Pair("DRIVER", listOf("DRIVER", "RIDE", "DIVE", "DIRE", "RIVER", "RED", "RID")),
    Pair("SINGER", listOf("SINGER", "SIGN", "RING", "SING", "REIN", "RISE", "SIN", "GIN")),
    Pair("DANCER", listOf("DANCER", "DANCE", "ACNE", "CANE", "DARE", "READ", "DEAR", "CAN", "RED", "DEN")),
    Pair("GUITAR", listOf("GUITAR", "TAG", "RUG", "AIR")),
    Pair("TRUMPET", listOf("TRUMPET", "TRUMP", "TRUE", "PURE", "TERM", "PER", "PET", "RUM")),
    Pair("VIOLIN", listOf("VIOLIN", "LION", "LOIN", "OIL", "NIL")),

    // 7-Letter Base Words
    Pair("BROTHER", listOf("BROTHER", "OTHER", "BROTH", "HERO", "BORE", "ROTE", "HER", "HOT", "BET")),
    Pair("FRIEND", listOf("FRIEND", "FIND", "FIRE", "FINE", "RIDE", "DIRE", "RED", "END", "FIN")),
    Pair("BUTTER", listOf("BUTTER", "TUBE", "TRUE", "BRUT", "RUB", "BET", "TUB")),
    Pair("CHEESE", listOf("CHEESE", "CHEE", "ECHE", "SEE", "SHE")),
    Pair("TRIANGLE", listOf("TRIANGLE", "ANGLE", "ALTER", "ALERT", "GREAT", "RANG", "RING", "GRANT", "ANT", "TAN")),
    Pair("COUNTRY", listOf("COUNTRY", "COUNT", "CRON", "TON", "TRY", "CRY", "OUT")),
    Pair("MOUNTAIN", listOf("MOUNTAIN", "MOUNT", "ANTI", "MAIN", "OMIT", "TIN", "MAN", "OUT")),
    Pair("DESERT", listOf("DESERT", "REST", "TREE", "REED", "SEER", "RED", "SET")),
    Pair("FOREST", listOf("FOREST", "SOFT", "FORT", "ROSE", "REST", "SORE", "TORE", "FOR", "SET", "ROT")),
    Pair("ISLAND", listOf("ISLAND", "LAND", "SAIL", "SAND", "LAID", "DIAL", "SLAD", "AID", "AND", "ADS")),
    Pair("JUNGLE", listOf("JUNGLE", "GLUE", "LUNG", "GEL", "JUG", "LUG")),
    Pair("HOSPITAL", listOf("HOSPITAL", "HOST", "PATH", "POST", "SHIP", "SHOP", "SPOT", "SOAP", "HALT", "TOP", "POT")),
    Pair("FACTORY", listOf("FACTORY", "FACTOR", "ACTOR", "CRAFT", "FORT", "ROTA", "COAT", "CART", "ART", "CAT", "TOY")),
    Pair("AIRPORT", listOf("AIRPORT", "PORT", "PAIR", "PART", "RAPT", "TRAP", "ROAR", "AIR", "PAR", "TOP")),
    Pair("ASTEROID", listOf("ASTEROID", "STAR", "ROAD", "TIDE", "RAID", "DIET", "READ", "SOAR", "RED", "SIT", "RAT")),
    Pair("SATURN", listOf("SATURN", "TURN", "RUST", "STAR", "NUT", "SUN", "RAN", "ANT")),
    Pair("NEPTUNE", listOf("NEPTUNE", "TUNE", "PUNT", "PENT", "PEN", "TEN", "NUT")),
    Pair("CUCUMBER", listOf("CUCUMBER", "CUBE", "CURB", "BERM", "CUM", "RUM")),
    Pair("SPAGHETTI", listOf("SPAGHETTI", "SPIT", "HEAT", "GATE", "PATH", "TAPE", "HAT", "GET", "PET", "PIT")),
    Pair("SANDWICH", listOf("SANDWICH", "SAND", "WASH", "HAND", "CHIN", "INCH", "WAND", "AND", "HAD", "CAN")),
    Pair("CHOCOLATE", listOf("CHOCOLATE", "COAT", "LATE", "COLA", "CHAT", "EACH", "TALE", "ACT", "CAT", "TEA")),
    Pair("ICECREAM", listOf("ICECREAM", "CREAM", "RACE", "ACRE", "MICE", "CAME", "ICE", "AIM", "ARM", "EAR")),
    Pair("CHICKEY", listOf("CHICKEY", "CHECK", "CHICK", "CHIC", "KEY", "ICE")),
    Pair("DRIVING", listOf("DRIVING", "RIND", "GRID", "GRIN", "RING", "DIG", "GIN", "RID")),
    Pair("NETWORK", listOf("NETWORK", "WORK", "WORE", "NOTE", "TONE", "RENT", "TOKE", "NET", "TOW", "ONE")),
    Pair("HACKER", listOf("HACKER", "HEAR", "HARE", "CARE", "ACHE", "RACK", "ARK", "CAR", "EAR", "ACE")),
    Pair("ROUTER", listOf("ROUTER", "ROUTE", "TOUR", "ROTE", "TRUE", "OUT", "ROU", "TOE")),
    Pair("CHEETAH", listOf("CHEETAH", "HEAT", "CHAT", "HATE", "EACH", "ACT", "HAT", "CAT", "TEA")),
    Pair("PENGUIN", listOf("PENGUIN", "PINE", "NINE", "PEN", "GUN", "PIN", "GIN")),
    Pair("SQUIRREL", listOf("SQUIRREL", "SURE", "RULE", "RISE", "RUE", "SIR")),
    // Additional 3 to 4-Letter Base Words
    Pair("COLD", listOf("COLD", "CLOD", "OLD", "COD")),
    Pair("MUG", listOf("MUG", "GUM")),
    Pair("WAR", listOf("WAR", "RAW")),
    Pair("FUN", listOf("FUN")),
    Pair("BOX", listOf("BOX")),
    Pair("FLY", listOf("FLY")),
    Pair("KEY", listOf("KEY")),
    Pair("PIG", listOf("PIG")),
    Pair("BAT", listOf("BAT", "TAB", "AT")),
    Pair("CUP", listOf("CUP")),
    Pair("LIP", listOf("LIP", "PIL")),
    Pair("BUG", listOf("BUG")),
    Pair("NUT", listOf("NUT", "TUN")),
    Pair("BOW", listOf("BOW")),
    Pair("HAT", listOf("HAT")),
    Pair("LOG", listOf("LOG")),
    Pair("FOX", listOf("FOX")),
    Pair("WEB", listOf("WEB")),
    Pair("ICE", listOf("ICE")),
    Pair("OWL", listOf("OWL", "LOW")),
    Pair("FIRE", listOf("FIRE", "RIFE", "FIR", "REF")),
    Pair("GOLD", listOf("GOLD", "OLD", "GOD")),
    Pair("KING", listOf("KING", "INK", "KIN")),
    Pair("LION", listOf("LION", "LOIN", "NIL", "ION")),
    Pair("WIND", listOf("WIND", "WIN", "DIN")),
    Pair("MOON", listOf("MOON", "MONO", "MOO")),
    Pair("STAR", listOf("STAR", "ARTS", "RATS", "TARS", "ART", "RAT", "TAR", "SAT")),
    Pair("WAVE", listOf("WAVE")),
    Pair("RAIN", listOf("RAIN", "RANI", "AIR", "RAN")),
    Pair("SNOW", listOf("SNOW", "SOWN", "NOW", "OWN", "SON")),

    // Additional 5-Letter Base Words
    Pair("SUPER", listOf("SUPER", "PURSE", "PURE", "SURE", "PER", "RUE", "SUP")),
    Pair("DREAM", listOf("DREAM", "ARMED", "MADRE", "READ", "DEAR", "MARE", "REAM", "ARM", "RAM", "RED")),
    Pair("SHINE", listOf("SHINE", "SHIN", "SINE", "HEN", "HIS", "SIN")),
    Pair("CLOUD", listOf("CLOUD", "LOUD", "COLD", "CLOD", "OLD", "COD")),
    Pair("FLASH", listOf("FLASH", "HALF", "LASH", "ASH", "HAS")),
    Pair("GREAT", listOf("GREAT", "GRATE", "RATE", "TEAR", "GATE", "GEAR", "ART", "ATE", "GET", "RAG")),
    Pair("BLAST", listOf("BLAST", "SALT", "SLAT", "LAST", "BAT", "SAT", "TAB", "ALT")),
    Pair("STORM", listOf("STORM", "MOST", "SORT", "MORT", "ROT", "TOM")),
    Pair("FLAME", listOf("FLAME", "MEAL", "MALE", "LAME", "FEAL", "ALE")),
    Pair("RIVER", listOf("RIVER", "RIVE", "IRE", "VIE")),
    Pair("GHOST", listOf("GHOST", "HOST", "SHOT", "GOT", "HOG")),
    Pair("SHARK", listOf("SHARK", "HARK", "ARK", "ASH")),
    Pair("SMART", listOf("SMART", "MART", "MATS", "TARS", "ARTS", "ARM", "MAT", "SAT", "RAT")),
    Pair("FAITH", listOf("FAITH", "FIAT", "HIT", "FAT")),
    Pair("VALLEY", listOf("VALLEY", "ALLY", "YELL", "VALE", "LAVE", "LAY")),
    Pair("GIANT", listOf("GIANT", "ANTI", "GAIN", "GIN", "TAG", "TAN", "ANT")),
    Pair("SPACE", listOf("SPACE", "PACE", "CAPE", "CASE", "ACE", "APE", "CAP", "ASP")),
    Pair("BRAVE", listOf("BRAVE", "BARE", "BEAR", "BAR", "BRA", "EAR")),
    Pair("HEART", listOf("HEART", "EARTH", "HEAR", "HEAT", "RATE", "TEAR", "EAR", "HAT", "ART")),
    Pair("LIGHT", listOf("LIGHT", "LIT", "HIT")),
    Pair("SOUND", listOf("SOUND", "DUNS", "ONUS", "SUN", "SOU")),
    Pair("CLEAR", listOf("CLEAR", "ACRE", "RACE", "CARE", "EAR", "CAR", "ARC", "ALE")),
    Pair("BLOOM", listOf("BLOOM", "LOOM", "LOB", "BOO")),
    Pair("CANDY", listOf("CANDY", "CAN", "ANY", "DAY", "AND")),
    Pair("PRIDE", listOf("PRIDE", "PRIED", "RIDE", "DIRE", "PIER", "RED", "RID", "DIP")),
    Pair("WORLD", listOf("WORLD", "WORD", "LORD", "ROW", "OLD")),
    Pair("CROWN", listOf("CROWN", "CORN", "CROW", "COW", "NOW", "OWN")),
    Pair("PIXELS", listOf("PIXELS", "PIXEL", "PILES", "LIPS", "PILE", "LIP", "LIE")),
    Pair("CHIEF", listOf("CHIEF", "CHIF", "CHEF", "ICE")),

    // Additional 6-Letter Base Words
    Pair("SILVER", listOf("SILVER", "SLIVER", "LIVE", "EVIL", "VEIL", "RILE", "VIE")),
    Pair("GOLDEN", listOf("GOLDEN", "LODGE", "LONE", "GOLD", "GONE", "OLD", "DEN", "LOG")),
    Pair("SUMMER", listOf("SUMMER", "MUSE", "SURE", "MUM", "SUM")),
    Pair("WINTER", listOf("WINTER", "WRITE", "TIER", "RENT", "TWIN", "NET", "TIE", "WIN")),
    Pair("SPRING", listOf("SPRING", "RING", "SING", "SIGN", "GRIN", "SPIN", "GIN", "PIN", "SIN")),
    Pair("PURPLE", listOf("PURPLE", "PURE", "RULE", "PULP", "PER", "PUP")),
    Pair("YELLOW", listOf("YELLOW", "YELL", "WELL", "LOW", "OWL")),
    Pair("BREEZE", listOf("BREEZE", "BEER", "BREE", "BEE")),
    Pair("CASTLE", listOf("CASTLE", "LACE", "CASE", "SEAT", "EAST", "LATE", "CAT", "ACT", "ALE")),
    Pair("DRAGON", listOf("DRAGON", "GROAN", "ORGAN", "DRAG", "ROAD", "RAN", "DOG", "RAG")),
    Pair("WIZARD", listOf("WIZARD", "DRAW", "RAID", "AIR", "RAW", "RAD")),
    Pair("PIRATE", listOf("PIRATE", "PART", "PAIR", "RATE", "TEAR", "RIPE", "AIR", "PET", "TAP", "ATE")),
    Pair("PLANET", listOf("PLANET", "PLANE", "PANEL", "PLANT", "PLATE", "LATE", "PEN", "PET", "NET")),
    Pair("ROCKET", listOf("ROCKET", "ROCK", "CORK", "COTE", "TORE", "CORE", "ROT", "TOE")),
    Pair("GARDEN", listOf("GARDEN", "DANGER", "RAGE", "GEAR", "READ", "DEN", "RED", "RAG")),
    Pair("FOREST", listOf("FOREST", "SOFT", "FORT", "ROSE", "REST", "FOR", "SET", "ROT")),
    Pair("DESERT", listOf("DESERT", "REST", "TREE", "REED", "SEER", "RED", "SET")),
    Pair("ISLAND", listOf("ISLAND", "LAND", "SAIL", "SAND", "LAID", "AID", "AND")),
    Pair("OCEANS", listOf("OCEANS", "OCEAN", "CANES", "CONES", "CAN", "ONE", "SON")),
    Pair("CANDLE", listOf("CANDLE", "LANCE", "CANE", "LAND", "DEAL", "LEAD", "CAN", "DEN", "AND")),
    Pair("SHADOW", listOf("SHADOW", "SHOW", "DASH", "WHO", "SOW", "HAD", "ASH")),
    Pair("MIRROR", listOf("MIRROR", "ROIM", "RIM")),
    Pair("WINDOW", listOf("WINDOW", "WIND", "DOWN", "OWN", "WIN", "NOW")),
    Pair("BOTTLE", listOf("BOTTLE", "BOLT", "BLOT", "LOB", "LOT", "TOE")),
    Pair("PENCIL", listOf("PENCIL", "CLIP", "LINE", "NIL", "PIN", "PEN", "LIE")),
    Pair("MARKET", listOf("MARKET", "MAKE", "RATE", "TEAM", "TEAR", "MEAT", "MAT", "ARM", "ART")),
    Pair("STREAM", listOf("STREAM", "MASTER", "STEAM", "TEAM", "MEAT", "RATE", "TEAR", "MAT", "ARM")),
    Pair("FLOWER", listOf("FLOWER", "WOLF", "FLOW", "FOWL", "LORE", "LOW", "ROW", "FOR")),
    Pair("MONKEY", listOf("MONKEY", "YOKE", "OMEN", "KEY", "MEN", "ONE")),
    Pair("JACKET", listOf("JACKET", "JACK", "TAKE", "TEAK", "ACT", "JET", "TEA")),

    // Additional 7 & 8-Letter Base Words
    Pair("DIAMOND", listOf("DIAMOND", "DOMAIN", "MONAD", "MIND", "NOMAD", "MAIN", "AID", "AND", "MAD")),
    Pair("RAINBOW", listOf("RAINBOW", "BRAIN", "BARN", "BRAN", "BROWN", "BROW", "RAIN", "AIR", "BAR", "ROW")),
    Pair("THUNDER", listOf("THUNDER", "UNDER", "TREND", "RUDE", "RED", "RUN", "NUT", "NET")),
    Pair("KINGDOM", listOf("KINGDOM", "DINGO", "MIND", "KING", "KIND", "DING", "DOG", "INK")),
    Pair("CRYSTAL", listOf("CRYSTAL", "CATS", "ARTS", "CART", "CAST", "STAR", "RAT", "CAT", "SAT")),
    Pair("TREASURE", listOf("TREASURE", "ERASE", "TEARS", "RATES", "TREES", "EAST", "REST", "SURE", "RAT", "ART")),
    Pair("SUNSHINE", listOf("SUNSHINE", "SHINE", "SHIN", "SINE", "NINE", "SUN", "SIN", "HEN")),
    Pair("MOONLIGHT", listOf("MOONLIGHT", "LIGHT", "NIGHT", "MONTH", "MILT", "MOON", "LOOM", "LIT", "HIT", "NOT")),
    Pair("STARLIGHT", listOf("STARLIGHT", "LIGHT", "START", "TRAIL", "RAIL", "LIT", "HIT", "AIR", "ART", "RAT")),
    Pair("EXPLORER", listOf("EXPLORER", "EXPLORE", "RELEX", "POLE", "PORE", "ROLE", "ROPE", "PER", "PRO")),
    Pair("ADVENTURE", listOf("ADVENTURE", "NATURE", "TRADE", "TREND", "RUDE", "DATE", "DEAR", "RED", "RAN", "ANT")),
    Pair("CHAMPION", listOf("CHAMPION", "CAMP", "PICO", "COIN", "INCH", "MAIN", "PIN", "CAN", "MAP")),
    Pair("WARRIOR", listOf("WARRIOR", "ARROW", "ROAR", "ROW", "WAR", "RAW")),
    Pair("VICTORY", listOf("VICTORY", "CITY", "TRIO", "TRY", "CRY", "TOY")),
    Pair("GUARDIAN", listOf("GUARDIAN", "GUARD", "DRAIN", "GRAIN", "RADIAN", "GARD", "RAD", "RAG", "AIR", "AND")),
    Pair("CREATOR", listOf("CREATOR", "ACTOR", "CRATE", "REACTOR", "RATER", "CART", "COAT", "CAT", "ART", "CAR")),
    // 3 & 4-Letter Base Words
    Pair("GLOW", listOf("GLOW", "OWL", "LOW")),
    Pair("BOLD", listOf("BOLD", "LOB", "OLD")),
    Pair("MINT", listOf("MINT", "TIN", "NIT")),
    Pair("FAST", listOf("FAST", "SAT", "AFT")),
    Pair("COLD", listOf("COLD", "OLD", "COD")),
    Pair("PALE", listOf("PALE", "PLEA", "LEAP", "PAL", "APE", "ALE")),
    Pair("MILD", listOf("MILD", "DIM", "LID", "MIL")),
    Pair("SOUL", listOf("SOUL", "SOU", "SOL")),
    Pair("RUST", listOf("RUST", "RUT", "SUT")),
    Pair("ZEAL", listOf("ZEAL", "ALE", "LEA")),
    Pair("DARK", listOf("DARK", "ARK", "RAD")),
    Pair("NEST", listOf("NEST", "NET", "TEN", "SET")),
    Pair("OAK", listOf("OAK", "KOA")),
    Pair("HERO", listOf("HERO", "HER", "ROE")),
    Pair("PALM", listOf("PALM", "LAMP", "MAP", "PAL", "LAP")),
    Pair("SOAP", listOf("SOAP", "ASP", "SAP")),
    Pair("ACRE", listOf("ACRE", "CARE", "RACE", "CAR", "ARC", "ARE")),
    Pair("LAKE", listOf("LAKE", "LEAK", "ALE")),
    Pair("WOLF", listOf("WOLF", "FLOW", "FOWL", "LOW")),
    Pair("PEAK", listOf("PEAK", "APE")),

    // 5-Letter Base Words
    Pair("BLAZE", listOf("BLAZE", "ABLE", "ZEAL", "ALE", "LAB")),
    Pair("CRAFT", listOf("CRAFT", "CART", "RAFT", "FACT", "ACT", "CAT", "ART")),
    Pair("FLOAT", listOf("FLOAT", "FLAT", "LOFT", "LOT", "OAT", "AFT")),
    Pair("GLORY", listOf("GLORY", "LOGY", "GYRO", "LOG")),
    Pair("REALM", listOf("REALM", "MARE", "REAM", "MEAL", "LAME", "ARM", "RAM", "EAR")),
    Pair("SPARK", listOf("SPARK", "PARK", "ARK", "PAR", "ASP", "SAP")),
    Pair("VORTEX", listOf("VORTEX", "VOTE", "ROTE", "TOE", "VEX")),
    Pair("YOUTH", listOf("YOUTH", "THOU", "TOY", "YOU", "OUT")),
    Pair("FLINT", listOf("FLINT", "LINT", "LIFT", "TIN", "LIT", "NIL")),
    Pair("STORM", listOf("STORM", "MOST", "SORT", "MORT", "ROT", "TOM")),
    Pair("CANDY", listOf("CANDY", "CAN", "ANY", "DAY", "AND")),
    Pair("SHINE", listOf("SHINE", "SHIN", "SINE", "HEN", "HIS", "SIN")),
    Pair("DREAM", listOf("DREAM", "READ", "DEAR", "MARE", "REAM", "ARM", "RED")),
    Pair("SMART", listOf("SMART", "MART", "TARS", "ARTS", "ARM", "MAT", "SAT")),
    Pair("GHOST", listOf("GHOST", "HOST", "SHOT", "GOT", "HOG")),
    Pair("PRIDE", listOf("PRIDE", "RIDE", "DIRE", "PIER", "RED", "RID", "DIP")),
    Pair("BLAST", listOf("BLAST", "SALT", "SLAT", "LAST", "BAT", "SAT", "ALT")),
    Pair("GIANT", listOf("GIANT", "ANTI", "GAIN", "GIN", "TAG", "TAN", "ANT")),
    Pair("FAITH", listOf("FAITH", "FIAT", "HIT", "FAT")),
    Pair("VALLEY", listOf("VALLEY", "ALLY", "YELL", "VALE", "LAY")),

    // 6-Letter Base Words
    Pair("SILVER", listOf("SILVER", "LIVE", "EVIL", "VEIL", "VIE")),
    Pair("GOLDEN", listOf("GOLDEN", "LONE", "GOLD", "GONE", "OLD", "DEN", "LOG")),
    Pair("SUMMER", listOf("SUMMER", "MUSE", "SURE", "MUM", "SUM")),
    Pair("WINTER", listOf("WINTER", "WRITE", "TIER", "RENT", "TWIN", "NET", "TIE", "WIN")),
    Pair("SPRING", listOf("SPRING", "RING", "SING", "SIGN", "GRIN", "SPIN", "GIN", "PIN")),
    Pair("PURPLE", listOf("PURPLE", "PURE", "RULE", "PULP", "PER", "PUP")),
    Pair("YELLOW", listOf("YELLOW", "YELL", "WELL", "LOW", "OWL")),
    Pair("DRAGON", listOf("DRAGON", "GROAN", "DRAG", "ROAD", "RAN", "DOG", "RAG")),
    Pair("WIZARD", listOf("WIZARD", "DRAW", "RAID", "AIR", "RAW", "RAD")),
    Pair("PIRATE", listOf("PIRATE", "PART", "PAIR", "RATE", "TEAR", "AIR", "PET", "TAP")),
    Pair("CANDLE", listOf("CANDLE", "LANCE", "CANE", "LAND", "DEAL", "LEAD", "CAN", "DEN")),
    Pair("SHADOW", listOf("SHADOW", "SHOW", "DASH", "WHO", "SOW", "HAD", "ASH")),
    Pair("SUNSET", listOf("SUNSET", "STUN", "NEST", "NET", "SET", "SUN", "TEN")),
    Pair("GALAXY", listOf("GALAXY", "GALA", "AGAL", "LAY", "GAL")),
    Pair("ORBIT", listOf("ORBIT", "ROBIT", "TRIO", "RIOT", "BIT", "ROT")),
    Pair("COMET", listOf("COMET", "COME", "COTE", "MET", "TOE")),
    Pair("ECLIPSE", listOf("ECLIPSE", "SLICE", "PIECE", "LICE", "CLIP", "ICE", "LIP")),
    Pair("METEOR", listOf("METEOR", "REMOTE", "MORE", "ROTE", "MET", "TOE")),
    Pair("NATURE", listOf("NATURE", "TUNE", "RUNE", "RATE", "TEAR", "ANT", "TAN")),
    Pair("ISLAND", listOf("ISLAND", "LAND", "SAIL", "SAND", "LAID", "AID", "AND")),

    // 7 & 8-Letter Base Words
    Pair("HARBOR", listOf("HARBOR", "HORBA", "BOAR", "ROAR", "BAR", "ROB")),
    Pair("HORIZON", listOf("HORIZON", "RHINO", "IRON", "HORN", "NOR")),
    Pair("BEACON", listOf("BEACON", "CANOE", "BACON", "CONE", "CAN", "ONE", "BAN")),
    Pair("BREEZE", listOf("BREEZE", "BEER", "BREE", "BEE")),
    Pair("COMPASS", listOf("COMPASS", "PASS", "CAMP", "SOAP", "MAP", "COP", "ASP")),
    Pair("JOURNEY", listOf("JOURNEY", "YOUR", "JURY", "RUNE", "RUN", "JOY")),
    Pair("PIONEER", listOf("PIONEER", "OPEN", "PEER", "PINE", "PEN", "PIN")),
    Pair("WARRIOR", listOf("WARRIOR", "ARROW", "ROAR", "ROW", "WAR", "RAW")),
    Pair("VICTORY", listOf("VICTORY", "CITY", "TRIO", "TRY", "CRY", "TOY")),
    Pair("CREATOR", listOf("CREATOR", "ACTOR", "CRATE", "CART", "COAT", "CAT", "ART")),
    Pair("DIAMOND", listOf("DIAMOND", "DOMAIN", "MIND", "NOMAD", "MAIN", "AID", "AND")),
    Pair("RAINBOW", listOf("RAINBOW", "BRAIN", "BROWN", "BROW", "RAIN", "AIR", "BAR", "ROW")),
    Pair("THUNDER", listOf("THUNDER", "UNDER", "TREND", "RUDE", "RED", "RUN", "NUT")),
    Pair("KINGDOM", listOf("KINGDOM", "MIND", "KING", "KIND", "DING", "DOG", "INK")),
    Pair("CRYSTAL", listOf("CRYSTAL", "CATS", "ARTS", "CART", "RAT", "CAT")),
    Pair("TREASURE", listOf("TREASURE", "ERASE", "TEARS", "RATES", "REST", "SURE", "RAT")),
    Pair("SUNSHINE", listOf("SUNSHINE", "SHINE", "SHIN", "SINE", "NINE", "SUN", "SIN")),
    Pair("MOONLIGHT", listOf("MOONLIGHT", "LIGHT", "NIGHT", "MONTH", "LOOM", "LIT", "HIT")),
    Pair("STARLIGHT", listOf("STARLIGHT", "LIGHT", "START", "RAIL", "LIT", "HIT", "AIR")),
    Pair("ADVENTURE", listOf("ADVENTURE", "NATURE", "TRADE", "TREND", "RUDE", "RED", "RAN")),
    Pair("SQUIRREL", listOf("SQUIRREL", "SURE", "RULE", "RISE"))
    )

    val levelNames = listOf(
        "Sunrise Valley", "Sunny Meadow", "Sandy Shore", "Forest Trail", "Misty Peaks",
        "Deep Ocean", "Desert Oasis", "Chilly Lake", "Green Field", "Cosmic Sky",
        "Golden Coast", "Volcano Rock", "Enchanted Woods", "Whispering Winds", "Crystal Cave",
        "Starlight Summit", "Autumn Breeze", "Shadowy Path", "Rainbow Falls", "Serene Oasis",
        "Dewy Grasslands", "Glimmering Grove", "Ancient Ruins", "Echoing Ravine", "Prismatic Lagoon",
        "Celestial Canopy", "Ember Valley", "Frozen Tundra", "Whispering Willow", "Mystic Garden",
        "Lotus Pond", "Saffron Steppes", "Jade Rainforest", "Silver Glacier", "Twilight Ridge"
    )
}
